# Generated by Django 4.1.5 on 2023-02-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_ventapropio_envio_alter_ventapropio_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedalclon',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='pedalreparar',
            name='presupuesto',
        ),
        migrations.AddField(
            model_name='pedalclon',
            name='descripcion',
            field=models.TextField(default='Descripcion del pedal', max_length=500),
        ),
        migrations.AddField(
            model_name='pedalreparar',
            name='falla',
            field=models.TextField(default='Falla', max_length=500),
        ),
    ]
