# Generated by Django 4.1.5 on 2023-02-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0011_alter_pedalclon_fechapedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedalclon',
            name='fechapedido',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedalreparar',
            name='fechapedido',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ventapropio',
            name='fechapedido',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
