# Generated by Django 4.1.5 on 2023-02-23 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_alter_pedalclon_fechapedido_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PedalReparar',
            new_name='Reparacion',
        ),
    ]
